import { describe, it, expect } from "vitest";
import { detectAiAttribution } from "../src/detector.js";

describe("AI Attribution Detector", () => {
  it("detects Co-Authored-By Claude trailer", () => {
    const msg = "feat: add user auth\n\nCo-Authored-By: Claude <noreply@anthropic.com>";
    const result = detectAiAttribution("Alice", "alice@example.com", msg);
    expect(result.isAiAttributed).toBe(true);
    expect(result.signatures).toContain("trailer:claude");
  });

  it("detects Cursor in commit message or trailers", () => {
    const msg = "refactor: api routes\n\nGenerated by Cursor";
    const result = detectAiAttribution("Bob", "bob@example.com", msg);
    expect(result.isAiAttributed).toBe(true);
    expect(result.signatures).toContain("message:cursor");
  });

  it("detects Aider / Copilot / Devin in author or committer", () => {
    const result1 = detectAiAttribution("Aider (v0.40)", "aider@local", "fix: types");
    expect(result1.isAiAttributed).toBe(true);

    const result2 = detectAiAttribution("github-actions[bot]", "actions@github.com", "chore: automated fix");
    expect(result2.isAiAttributed).toBe(true);

    const result3 = detectAiAttribution("Devin AI", "devin@cognition.ai", "feat: payment gateway");
    expect(result3.isAiAttributed).toBe(true);
  });

  it("returns false for genuine human commits without AI signatures", () => {
    const msg = "docs: update install guide";
    const result = detectAiAttribution("Linus Torvalds", "linus@kernel.org", msg);
    expect(result.isAiAttributed).toBe(false);
    expect(result.signatures).toHaveLength(0);
  });
});
